server:
    port: 8760

spring:
    application:
        name: arco
    cloud:
        gateway:
            routes:
                - id: service
                  uri: lb://service
                  predicates:
                      - Path=/service/**
                  filters:
                      - StripPrefix=1
                - id: idea
                  uri: lb://idea
                  predicates:
                      - Path=/idea/**
                  filters:
                      - StripPrefix=1
                - id: eureka
                  uri: lb://idea
                  predicates:
                      - Path=/eureka/**

info:
    app:
        name: ${spring.application.name}

eureka:
    client:
        registerWithEureka: true
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
        healthcheck:
            enabled: true

management:
    endpoints:
        web:
            exposure:
                include:
                    - mappings
                    - env
                    - health
                    - info
